spring:
  datasource:
    username: root
    password: 2000623Feisdhy
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blockchain?useUnicode=true&characterEncoding=utf-8
  data:
    redis:
      port: 6379
      database: 0
      host: localhost

#mybatis-plus:
# configuration:
#  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
